name = "lean-metaprogramming"
version = "0.1.0"
defaultTargets = ["lean-metaprogramming"]

[[require]]
name = "lean-slides"
git = "https://github.com/0art0/lean-slides.git"
rev = "master"

[[lean_lib]]
name = "LeanMetaprogramming"